### ISSUE TITLE
PyPI package is older than GitHub repo

### ISSUE THREAD

**Issue by abearab** [gdcc/easyDataverse#19]
Maybe you can update your package here – https://pypi.org/project/easyDataverse/

<img width="1110" alt="image" src="https://github.com/gdcc/easyDataverse/assets/53412130/36601a5c-7baa-4bde-9746-43a8919393c1">

**Comment by JR-1991** [comment]
Sorry for the delay, @abearab, and thanks for submitting this issue! The new version has just been pushed to PyPI 🙌
