### ISSUE TITLE
DATAVERSE_API_TOKEN vs API_TOKEN

### ISSUE THREAD

**Issue by atrisovic** [gdcc/easyDataverse#6]
Maybe this error `No 'API_TOKEN' found in the environment.` should refer to `DATAVERSE_API_TOKEN` instead of `API_TOKEN ` as that is what the user sets/exports.

https://github.com/gdcc/easyDataverse/blob/81d8d45bdd41949e01d5b422803e9aed80b697c7/easyDataverse/core/dataset.py#L470

**Comment by JR-1991** [comment]
Thanks @atrisovic! Updated the error message.
